version: '3'

services:
  djangoapp:
    build: .
    env_file:
      - config/db/database_env
      - config/django_env
      - .env
    environment:
      DOCKER_ENV: 'on'
    volumes:
      - requirements_volume:/opt/services/djangoapp/requirements
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
      # these three are for a development environment:
      - ./formative:/opt/services/djangoapp/src/formative
      - ./templates:/opt/services/djangoapp/src/templates
      - ./assets/bundles:/opt/services/djangoapp/src/assets/bundles
    depends_on:
      - database
      - postfix

  nginx:
    image: nginx:1.21
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    depends_on:
      - djangoapp

  database:
    image: postgres:13
    command: postgres -c shared_buffers=512MB
    env_file:
      - config/db/database_env
      - .env
    ports:
      # a port map for the development environment:
      - 5432:5432
    volumes:
      - database_volume:/var/lib/postgresql/data
  
  redis:
    image: redis:6

  postfix:
    image: juanluisbaptiste/postfix:1.3
    env_file:
      - config/postfix_env
      - .env
    volumes:
      - postfix_volume:/var/spool/postfix

volumes:
  database_volume:
  requirements_volume:
  static_volume:
  media_volume:
  postfix_volume:
