# Generated by Django 4.0.4 on 2022-05-11 20:11

import django.contrib.sites.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('formative', '0007_alter_collectionblock_align_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('site_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sites.site')),
                ('time_zone', models.CharField(max_length=32)),
            ],
            bases=('sites.site',),
            managers=[
                ('objects', django.contrib.sites.models.SiteManager()),
            ],
        ),
        migrations.AddField(
            model_name='program',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='programs', related_query_name='program', to='formative.site'),
        ),
    ]
