#!/command/with-contenv sh

cd /opt/services/djangoapp/requirements
touch requirements.txt
pip install -r requirements.txt

#python3 manage.py collectstatic --noinput
#if [ "$AUTO_MIGRATE" != "" ]; then
#  python3 manage.py migrate --noinput
#fi
